# Generated by Django 3.2 on 2021-04-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('create_uid', models.IntegerField(blank=True, default=0, verbose_name='创建用户')),
                ('write_uid', models.IntegerField(blank=True, default=0, verbose_name='修改用户')),
                ('write_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('active', models.BooleanField(default=True, verbose_name='是否删除?')),
                ('name', models.CharField(help_text='姓名', max_length=24, verbose_name='姓名')),
                ('email', models.EmailField(help_text='邮箱', max_length=255, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '书籍',
                'db_table': 'test_authors',
            },
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('create_uid', models.IntegerField(blank=True, default=0, verbose_name='创建用户')),
                ('write_uid', models.IntegerField(blank=True, default=0, verbose_name='修改用户')),
                ('write_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('active', models.BooleanField(default=True, verbose_name='是否删除?')),
                ('name', models.CharField(help_text='书名', max_length=512, verbose_name='书名')),
                ('state', models.CharField(blank=True, choices=[('draft', '草稿'), ('shop', '上架'), ('stock-out', '缺货')], default='draft', max_length=12, verbose_name='状态')),
                ('abstract', models.TextField(default=None, verbose_name='摘要')),
                ('pub_data', models.DateField(verbose_name='出版日期')),
            ],
            options={
                'verbose_name': '书籍',
                'db_table': 'test_books',
            },
        ),
    ]
